added new files

diff --git a/.github/workflows/ciscan.yml b/.github/workflows/ciscan.yml
--- a/.github/workflows/ciscan.yml
+++ b/.github/workflows/ciscan.yml
@@ -33,35 +33,50 @@ jobs:
         chmod +x cortexcli
         ./cortexcli --version
         
-    # Do AppSec Code Scanning
-    - name: Set up Node.js
-      uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6
-      with:
-        node-version: 22
-
-    - name: Verify Node.js Version
-      run: node -v
+    # Do CWP image scanning
+    - name: CWP Image Scan Dependency
+      run: sudo apt install libhyperscan5 jq -y
       
-    - name: Run Cortex CLI Code Scan
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
+
+    - name: Build Image and export image ID
       run: |
-        ./cortexcli \
+        docker build -t $IMAGE_NAME .
+        image_id=$(docker inspect $IMAGE_NAME --format='{{.Id}}')
+        echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
+
+        
+    - name: Cortex CLI Image Scan
+      run: |
+        results=$(sudo ./cortexcli \
           --api-base-url "${CORTEX_API_URL}" \
           --api-key "${CORTEX_API_KEY}" \
           --api-key-id "${CORTEX_API_KEY_ID}" \
-          code scan \
-          --directory "${{github.workspace}}" \
-          --repo-id "${{github.repository}}" \
-          --branch "${{github.ref_name}}" \
-          --source "GITHUB_ACTIONS" \
-          --create-repo-if-missing \
-          --output json \
-          --output-file-path "appsec-${{ env.OUTPUT_FILE }}"
-    
-    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
-      with:
-        name: appsec-scan-results
-        path: "appsec-${{ env.OUTPUT_FILE }}"
-  
+          --log-levl INFO
+          image scan \
+          --timeout 600 \
+          --name $IMAGE_NAME \
+          --output-format json \
+          $IMAGE_NAME)
+        image_id="$(echo $results | grep -oP '(?<="image_id":")[^"]*')"
+
+        if [[ -z "$image_id" ]]; then
+            echo "❌ Failed to get results from CortexCLI"
+            cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
+            exit 1
+        fi
+        echo "CortexCLI scan completed successfully. Image ID: ${image_id}"
+        echo "$results" | jq '.'
+        echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
+
+    - name: Wait for results
+      run: | 
+        echo "Waiting for Cortex to process image $IMAGE_NAME. Image Id: ${IMAGE_ID}"
+        sleep ${WAIT}
 
     - name: Get Results
       run : |
