Lets GO

diff --git a/.github/workflows/ciscan.yml b/.github/workflows/ciscan.yml
--- a/.github/workflows/ciscan.yml
+++ b/.github/workflows/ciscan.yml
@@ -46,77 +46,67 @@ jobs:
 
     - name: Cortex CLI Image Scan
       run: |
-        results=$(sudo ./cortexcli \
+        sudo ./cortexcli \
           --api-base-url "${CORTEX_API_URL}" \
           --api-key "${CORTEX_API_KEY}" \
           --api-key-id "${CORTEX_API_KEY_ID}" \
           --log-level INFO \
           --name $IMAGE_NAME \
           --output-format json \
-           image scan $IMAGE_NAME)
-        image_id="$(echo $results | grep -oP '(?<="image_id":")[^"]*')"
+           image scan $IMAGE_NAME
 
-        if [[ -z "$image_id" ]]; then
-            echo "❌ Failed to get results from CortexCLI"
-            cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
-            exit 1
-        fi
-        echo "CortexCLI scan completed successfully. Image ID: ${image_id}"
-        echo "$results" | jq '.'
-        echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
+    # - name: Wait for results
+    #   run: | 
+    #     echo "Waiting for Cortex to process image $IMAGE_NAME. Image Id: ${IMAGE_ID}"
+    #     sleep ${WAIT}
 
-    - name: Wait for results
-      run: | 
-        echo "Waiting for Cortex to process image $IMAGE_NAME. Image Id: ${IMAGE_ID}"
-        sleep ${WAIT}
+    # - name: Get Results
+    #   run : |
+    #     echo "Obtaining findings of image: $IMAGE_NAME. Image Id: $IMAGE_ID"
+    #     start_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/start_xql_query" -d '
+    #         {
+    #             "request_data": {
+    #                 "query": "dataset = findings | filter xdm.finding.asset_name = \"'$IMAGE_ID'\""
+    #             }
+    #         }')
+    #     query_id=$(echo "$start_response" | jq -r '.reply')
 
-    - name: Get Results
-      run : |
-        echo "Obtaining findings of image: $IMAGE_NAME. Image Id: $IMAGE_ID"
-        start_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/start_xql_query" -d '
-            {
-                "request_data": {
-                    "query": "dataset = findings | filter xdm.finding.asset_name = \"'$IMAGE_ID'\""
-                }
-            }')
-        query_id=$(echo "$start_response" | jq -r '.reply')
+    #     if [[ "$query_id" != *"_inv" ]]; then
+    #         echo "❌ Failed to start XQL query. Response details:"
+    #         echo "$start_response"
+    #         exit 1
+    #     fi
 
-        if [[ "$query_id" != *"_inv" ]]; then
-            echo "❌ Failed to start XQL query. Response details:"
-            echo "$start_response"
-            exit 1
-        fi
-
-        echo "XQL Query started successfully. Query ID: ${query_id}"
+    #     echo "XQL Query started successfully. Query ID: ${query_id}"
 
 
-        # Define initial status
-        echo "Retrieving results for Query ID: ${query_id}. Waiting for completion (pending_flag=true)..."
-        status="PENDING"
+    #     # Define initial status
+    #     echo "Retrieving results for Query ID: ${query_id}. Waiting for completion (pending_flag=true)..."
+    #     status="PENDING"
 
-        while [[ "$status" == "PENDING" ]]; do
-            # Execute API call to get results
-            results_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/get_query_results" -d '
-                {
-                    "request_data": {
-                        "query_id": "'$query_id'", 
-                        "pending_flag": true, 
-                        "limit": 100, 
-                        "format": "json"
-                    }
-                }')
-            status=$(echo "$results_response" | jq -r '.reply.status')
-            sleep 10
-        done
+    #     while [[ "$status" == "PENDING" ]]; do
+    #         # Execute API call to get results
+    #         results_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/get_query_results" -d '
+    #             {
+    #                 "request_data": {
+    #                     "query_id": "'$query_id'", 
+    #                     "pending_flag": true, 
+    #                     "limit": 100, 
+    #                     "format": "json"
+    #                 }
+    #             }')
+    #         status=$(echo "$results_response" | jq -r '.reply.status')
+    #         sleep 10
+    #     done
 
-        echo "Retrieve results status: $status"
-        # Print the full response for troubleshooting
-        if [[ "$status" == "SUCCESS" ]]; then
-          echo "$results_response" | jq '.reply.results.data' | jq 'map(.image_name = "'$IMAGE_NAME'")' > "image-${{ env.OUTPUT_FILE }}"
-        fi
+    #     echo "Retrieve results status: $status"
+    #     # Print the full response for troubleshooting
+    #     if [[ "$status" == "SUCCESS" ]]; then
+    #       echo "$results_response" | jq '.reply.results.data' | jq 'map(.image_name = "'$IMAGE_NAME'")' > "image-${{ env.OUTPUT_FILE }}"
+    #     fi
 
     
-    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
-      with:
-        name: image-scan-results
-        path: "image-${{ env.OUTPUT_FILE }}"
+    # - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
+    #   with:
+    #     name: image-scan-results
+    #     path: "image-${{ env.OUTPUT_FILE }}"
